### ISSUE TITLE
Error login in from Gingerbread.

### ISSUE THREAD

**Issue by jeremyvillalobos** [box/box-android-apptoapp-sdk#17]
I get this error only on a Gingerbread device 

W/System.err( 5892): javax.net.ssl.SSLHandshakeException: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:477)
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
W/System.err( 5892):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpConnection.setupSecureSocket(HttpConnection.java:185)
W/System.err( 5892):    at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:433)
W/System.err( 5892):    at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeConnection(HttpsURLConnectionImpl.java:387)
W/System.err( 5892):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.retrieveResponse(HttpURLConnectionImpl.java:1018)
W/System.err( 5892):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:726)
W/System.err( 5892):    at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:121)
W/System.err( 5892):    at com.box.androidlib.BoxSynchronous.saxRequest(BoxSynchronous.java:1239)
W/System.err( 5892):    at com.box.androidlib.BoxSynchronous.getTicket(BoxSynchronous.java:146)
W/System.err( 5892):    at com.box.androidlib.Box$1.run(Box.java:325)
W/System.err( 5892): Caused by: java.security.cert.CertificateException: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:161)
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:664)
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:474)
W/System.err( 5892):    ... 10 more
W/System.err( 5892): Caused by: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
W/System.err( 5892):    at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1504)
W/System.err( 5892):    at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:399)
W/System.err( 5892):    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:197)
W/System.err( 5892):    at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:156)
W/System.err( 5892):    ... 13 more
W/System.err( 5892): Caused by: java.security.SignatureException: Signature was not verified
W/System.err( 5892):    at org.apache.harmony.security.provider.cert.X509CertImpl.fastVerify(X509CertImpl.java:562)
W/System.err( 5892):    at org.apache.harmony.security.provider.cert.X509CertImpl.verify(X509CertImpl.java:487)
W/System.err( 5892):    at org.bouncycastle.jce.provider.CertPathValidatorUtilities.verifyX509Certificate(CertPathValidatorUtilities.java:1551)
W/System.err( 5892):    at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1496)
W/System.err( 5892):    ... 16 more

Other android flavors work ok (Kindle, KitKat).  The issue also affects Box.com official app.  Gingerbread was working ok before.

**Comment by RicoYao** [comment]
Thank you for the report. Could you please give us the specific device type (e.g. Motorola Droid) and operating system level (e.g. 2.3.4) on which you ran into this?

**Comment by jeremyvillalobos** [comment]
It is a Galaxy Note (generation one) with Gingerbread 2.3.6

The Official app reports a Network Error.

The developer's module code found here:

https://github.com/box/box-android-sdk

gives this error stack trace:

W/System.err( 5892): javax.net.ssl.SSLHandshakeException:
org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not
validate certificate signature.
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:477)
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
W/System.err( 5892):    at
org.apache.harmony.luni.internal.net.www.protocol.http.HttpConnection.setupSecureSocket(HttpConnection.java:185)
W/System.err( 5892):    at
org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:433)
W/System.err( 5892):    at
org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeConnection(HttpsURLConnectionImpl.java:387)
W/System.err( 5892):    at
org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.retrieveResponse(HttpURLConnectionImpl.java:1018)
W/System.err( 5892):    at
org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:726)
W/System.err( 5892):    at
org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:121)
W/System.err( 5892):    at
com.box.androidlib.BoxSynchronous.saxRequest(BoxSynchronous.java:1239)
W/System.err( 5892):    at
com.box.androidlib.BoxSynchronous.getTicket(BoxSynchronous.java:146)
W/System.err( 5892):    at com.box.androidlib.Box$1.run(Box.java:325)
W/System.err( 5892): Caused by: java.security.cert.CertificateException:
org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not
validate certificate signature.
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:161)
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:664)
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native
Method)
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:474)
W/System.err( 5892):    ... 10 more
W/System.err( 5892): Caused by:
org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not
validate certificate signature.
W/System.err( 5892):    at
org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1504)
W/System.err( 5892):    at
org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:399)
W/System.err( 5892):    at
java.security.cert.CertPathValidator.validate(CertPathValidator.java:197)
W/System.err( 5892):    at
org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:156)
W/System.err( 5892):    ... 13 more
W/System.err( 5892): Caused by: java.security.SignatureException: Signature
was not verified
W/System.err( 5892):    at
org.apache.harmony.security.provider.cert.X509CertImpl.fastVerify(X509CertImpl.java:562)
W/System.err( 5892):    at
org.apache.harmony.security.provider.cert.X509CertImpl.verify(X509CertImpl.java:487)
W/System.err( 5892):    at
org.bouncycastle.jce.provider.CertPathValidatorUtilities.verifyX509Certificate(CertPathValidatorUtilities.java:1551)
W/System.err( 5892):    at
org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1496)
W/System.err( 5892):    ... 16 more

On Sat, Sep 28, 2013 at 11:49 AM, Rico Yao notifications@github.com wrote:

> Thank you for the report. Could you please give us the specific device
> type (e.g. Motorola Droid) and operating system level (e.g. 2.3.4) on which
> you ran into this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/box/box-android-sdk/issues/17#issuecomment-25300446
> .

## 

Jeremy Villalobos
Practical Android Apps
http://www.practicalandroidapps.com/
http://www.youtube.com/user/PdfToSpeech
https://plus.google.com/u/0/b/109848961267144267628/109848961267144267628/posts

**Comment by RicoYao** [comment]
Hello, the issue should now be resolved. Could you please give it another try and let me know if it succeeds? Thanks, and our apologies for the error.
